language: node_js
node_js:
- 8
deploy:
  provider: firebase
  skip_cleanup: true
  project: linear-obsession
cache:
  directories:
  - node_modules
script:
- yarn build
env:
  global:
    secure: S9O7lIemNKpKjnb/kpVfqAoNOZL4AQt0tq1So9sSCSWH0vsRCy8z3deUhz0pr+EEk/dGQ3CvmADIMfAWwdIT5F6cz+kQldOtHwUy3ujIOMjePGFG/lDAfIdaPVA8lndHYA4U3v/4RFOqnU3zKOM72uIbqibmohiMbyfyc3cVPllWHA0r0Jp6aLdsgW0hEReZBNFpZFybzfs9qfDxdps9RAZvh2D5ssAXvwEw7PbaNJqCmor7lFLaRFBNHNItaUSR+eeCmwMgmnAD5BZv76gVM/RxdBSb2G2Ale618L0OegA/nAADFfL1KufJvAqhzRgRB7EOa8jSU7p2fiis6YQPtu1gCbsBUyy2qcmEFUC3bniZGG3kV9rdMuBQgUvGdrHhuBJr9Xyck9RIXHH+bZ44I+QsZgjCqlvV1xtnfZFJKcqq1lWqQ3rYwmXYOVy10ISaVnt4TIZYTmKffoxoVOgKPLOW3+W4jUYT+nj4okeL5dC7/pXG/UgVeAXjhnAThdDJU1I8qv9GISlZZPPl0HRWdYnE/luCc8/gWV0zXO1nGM0cbbH98IP/HUJm0X0RerW5iJBLiJwnSJfZY4IvQzinXfkEB1DVJhFbW7eNT1PnSDWY/tQDl8n6xfQ9rDGD4FTTYV6iUTGNvNSHMkmslIhu3lSahboH64xpvUQ07/Udyz0=
